import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = (process.argv[2] === "production");

// CHANGE THIS PATH to the exact location of your local Obsidian vault plugins directory
const vaultPluginDir = "/Users/beth/obsidian/Personal Knowledge Management/.obsidian/plugins/smart-tagger-local";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		...builtins],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `${vaultPluginDir}/main.js`,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}